version: "3.9"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ChatApplicationAPI
      MYSQL_USER: appuser
      MYSQL_PASSWORD: password
      
  redis:
    image: 'redis:5-alpine'
    ports:
      - '6379:6379'
      
  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - redis
      - db
    volumes:
      - .:/ChatApplicationAPI

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"  

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
  
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/ChatApplicationAPI
    ports:
      - "3001:3000"
    depends_on:
      - db
      - sidekiq
      - rabbitmq
      - elasticsearch